### ISSUE TITLE
Assertion failed when not applying the option pyvex.set_iropt_level(0)

### ISSUE THREAD

**Issue by penhoi** [jeffball55/rop_compiler#5]
Hi,

I found that pyrop successes to work when applying the option pyvex.set_iropt_level(0), but fails to work when applying the option pyvex.set_iropt_level(1).  Is there something wrong with the PyvexEvaluator class?

The following is my tests.

-------------Code for lifting-------------------
({LoadMem : 1},         '\x5f\xc3'), # pop rdi; ret

------------------TEST1: success----------------

pyvex.set_iropt_level(0)

irsbs[0].pp()
IRSB {
   t0:Ity_I64 t1:Ity_I64 t2:Ity_I64 t3:Ity_I64 t4:Ity_I64 t5:Ity_I64 t6:Ity_I64 t7:Ity_I64

   00 | IR-NoOp
   01 | IR-NoOp
   02 | IR-NoOp
   03 | IR-NoOp
   04 | IR-NoOp
   05 | IR-NoOp
   06 | IR-NoOp
   07 | IR-NoOp
   08 | IR-NoOp
   09 | IR-NoOp
   10 | IR-NoOp
   11 | IR-NoOp
   12 | IR-NoOp
   13 | IR-NoOp
   14 | IR-NoOp
   15 | ------ IMark(0x40000, 1, 0) ------
   16 | t1 = GET:I64(rsp)
   17 | t0 = LDle:I64(t1)
   18 | t5 = Add64(t1,0x0000000000000008)
   19 | PUT(rsp) = t5
   20 | PUT(rdi) = t0
   21 | PUT(pc) = 0x0000000000040001
   22 | ------ IMark(0x40001, 1, 0) ------
   23 | t2 = GET:I64(rsp)
   24 | t3 = LDle:I64(t2)
   25 | t4 = Add64(t2,0x0000000000000008)
   26 | PUT(rsp) = t4
   27 | t6 = Sub64(t4,0x0000000000000080)
   28 | ====== AbiHint(0xt6, 128, t3) ======
   29 | PUT(pc) = t3
   30 | t7 = GET:I64(pc)
   NEXT: PUT(rip) = t7; Ijk_Ret
}
2016-12-22 09:55:58,194 - GadgetClassifier - DEBUG - Found gadget: LoadMem(Address: 0x40000, Complexity 1.33, Stack 0x10, Ip 0x8, Output: [rdi], Inputs [rsp], Params [0x0L])

------------------TEST1: Failed----------------
pyvex.set_iropt_level(1)

pydev debugger: starting
irsbs[0].pp()
IRSB {
   t0:Ity_I64 t1:Ity_I64 t2:Ity_I64 t3:Ity_I64 t4:Ity_I64 t5:Ity_I64 t6:Ity_I64 t7:Ity_I64

   00 | ------ IMark(0x40000, 1, 0) ------
   01 | t1 = GET:I64(rsp)
   02 | t0 = LDle:I64(t1)
   03 | t5 = Add64(t1,0x0000000000000008)
   04 | PUT(rsp) = t5
   05 | PUT(rdi) = t0
   06 | PUT(pc) = 0x0000000000040001
   07 | ------ IMark(0x40001, 1, 0) ------
   08 | t3 = LDle:I64(t5)
   09 | t4 = Add64(t5,0x0000000000000008)
   10 | PUT(rsp) = t4
   11 | t6 = Sub64(t4,0x0000000000000080)
   12 | ====== AbiHint(0xt6, 128, t3) ======
   NEXT: PUT(rip) = t3; Ijk_Ret
}
AssertionError: {<class 'rop_compiler.gadget.LoadMem'>: 1} != {}
- {<class 'rop_compiler.gadget.LoadMem'>: 1}
+ {}

------------------End tests--------------

**Comment by jeffball55** [comment]
After talking with the angr devs, it looks like pyvex returns a smaller set of statements when pyvex.set_iropt_level is not 0.  Specifically, this was causing a problem:

With iropt_level set to 0:
```
>>> pyvex.IRSB(binascii.unhexlify("4159c35dc3554889e548"), 0x40064c, archinfo.ArchAMD64()).pp()                                                                                                       
IRSB {
   t0:Ity_I64 t1:Ity_I64 t2:Ity_I64 t3:Ity_I64 t4:Ity_I64 t5:Ity_I64 t6:Ity_I64 t7:Ity_I64

   00 | ------ IMark(0x40064c, 2, 0) ------
   01 | t1 = GET:I64(rsp)
   02 | t0 = LDle:I64(t1)
   03 | t5 = Add64(t1,0x0000000000000008)
   04 | PUT(rsp) = t5
   05 | PUT(r9) = t0
   06 | PUT(pc) = 0x000000000040064e
   07 | ------ IMark(0x40064e, 1, 0) ------
   08 | t2 = GET:I64(rsp)
   09 | t3 = LDle:I64(t2)
   10 | t4 = Add64(t2,0x0000000000000008)
   11 | PUT(rsp) = t4
   12 | t6 = Sub64(t4,0x0000000000000080)
   13 | ====== AbiHint(0xt6, 128, t3) ======
   14 | PUT(pc) = t3
   15 | t7 = GET:I64(pc)
   NEXT: PUT(rip) = t7; Ijk_Ret
}
```

With iropt_level set to 1:
```
>>> pyvex.IRSB(binascii.unhexlify("4159c35dc3554889e548"), 0x40064c, archinfo.ArchAMD64()).pp()
IRSB {
   t0:Ity_I64 t1:Ity_I64 t2:Ity_I64 t3:Ity_I64 t4:Ity_I64 t5:Ity_I64 t6:Ity_I64 t7:Ity_I64

   00 | ------ IMark(0x40064c, 2, 0) ------
   01 | t1 = GET:I64(rsp)
   02 | t0 = LDle:I64(t1)
   03 | t5 = Add64(t1,0x0000000000000008)
   04 | PUT(rsp) = t5
   05 | PUT(r9) = t0
   06 | PUT(pc) = 0x000000000040064e
   07 | ------ IMark(0x40064e, 1, 0) ------
   08 | t3 = LDle:I64(t5)
   09 | t4 = Add64(t5,0x0000000000000008)
   10 | PUT(rsp) = t4
   11 | t6 = Sub64(t4,0x0000000000000080)
   12 | ====== AbiHint(0xt6, 128, t3) ======
   NEXT: PUT(rip) = t3; Ijk_Ret
}
```

pyvex uses those extra statements at the end to determine how to set the PC register after the gadget.  Because they aren't there when iropt_level is 1, the classifier doesn't think it can set the PC, and thus the gadget can't be used.  

Note that this has recently become more of a problem as since I first released pyrop, cle now sets the global iropt_level to 1 when cle.Loader is called.  To fix this I've added a pyvex.set_iropt_level(0) call just before the classifier calls pyvex.IRSB.  After the classifier is finished, it can be set back (that's the only part of pyrop that calls pyvex.IRSB).
